services:
  db:
    image: postgres:15
    container_name: akhmad_local_db
    environment:
      POSTGRES_DB: akhmadshunhaji_dev
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: LocalOnlyStrongPassword
    ports:
      - "5433:5432"
    volumes:
      - akhmad_local_db_data:/var/lib/postgresql/data

volumes:
  akhmad_local_db_data: