services:
  db:
    image: postgres:15
    container_name: arif_local_db
    environment:
      POSTGRES_DB: ariffaizin_dev
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: LocalOnlyStrongPassword
    ports:
      - "5433:5432"
    volumes:
      - arif_local_db_data:/var/lib/postgresql/data

volumes:
  arif_local_db_data: